apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: processor-gateway
  namespace: fluxcdpoc
spec:
  interval: 30s
  ref:
    branch: main
  url: https://rajeev-cs/processor-gateway.git