---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: processor-gateway
  namespace: fluxcdpoc
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/rajeev-cs/processor-gateway.git
