apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: processor-gateway
  namespace: fluxcdpoc
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s_nginxapp_sot
