apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: processor-gateway
  namespace: fluxcdpoc
spec:
  interval: 30s
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: processor-gateway