### invoke job
POST http://localhost:4444/fabric/v4/projects/johan/agentinvoke/job-chain-sendmsg/services/input
Content-Type: application/json
Authorization: bearer eyJraWQiOiJfM1g1aWpvcGdTSm0tSmVmdWJQenh5RS1XWGw3UzJqSVZDLXRNWnNiRG9BIiwiYWxnIjoiRWREU0EifQ.eyJiZWFyZXIiOiJ1c2VyIiwiaWF0IjoxNjA0Njg1NDk2LCJleHAiOjE2MDQ3NzE4OTYsInN1YiI6IjM3MGY3ZWM2LTQ2NmYtNGEzNi1iYjVmLWJjMjRmMzRkYTIxYiIsImF1ZCI6ImNvcnRleCIsImlzcyI6ImNvZ25pdGl2ZXNjYWxlLmNvbSJ9.EwFYL18rSUYtTu4eW6FJVGoNZ4ww31B2vIlQQpaXy8C1Fn-xzwJ92Ix3yi9hkIUnuUC6qyMFSfsXxztOLNjPDQ

{ "payload" : {"text": "hello"}}

> {%
client.global.set("JobactivationId", response.body.activationId);
%}

### get activations
GET http://localhost:4444/fabric/v4/projects/cogscale/agentinvoke/cortex%2Fhubbble_agent/activations/{{JobactivationId}}
Content-Type: application/json
Authorization: bearer eyJraWQiOiJfM1g1aWpvcGdTSm0tSmVmdWJQenh5RS1XWGw3UzJqSVZDLXRNWnNiRG9BIiwiYWxnIjoiRWREU0EifQ.eyJiZWFyZXIiOiJ1c2VyIiwiaWF0IjoxNjA0Njg1NDk2LCJleHAiOjE2MDQ3NzE4OTYsInN1YiI6IjM3MGY3ZWM2LTQ2NmYtNGEzNi1iYjVmLWJjMjRmMzRkYTIxYiIsImF1ZCI6ImNvcnRleCIsImlzcyI6ImNvZ25pdGl2ZXNjYWxlLmNvbSJ9.EwFYL18rSUYtTu4eW6FJVGoNZ4ww31B2vIlQQpaXy8C1Fn-xzwJ92Ix3yi9hkIUnuUC6qyMFSfsXxztOLNjPDQ

###
GET http://localhost:4444/fabric/v4/projects/johan/activations
Content-Type: application/json
Authorization: bearer eyJraWQiOiJfM1g1aWpvcGdTSm0tSmVmdWJQenh5RS1XWGw3UzJqSVZDLXRNWnNiRG9BIiwiYWxnIjoiRWREU0EifQ.eyJiZWFyZXIiOiJ1c2VyIiwiaWF0IjoxNjA0Njg1NDk2LCJleHAiOjE2MDQ3NzE4OTYsInN1YiI6IjM3MGY3ZWM2LTQ2NmYtNGEzNi1iYjVmLWJjMjRmMzRkYTIxYiIsImF1ZCI6ImNvcnRleCIsImlzcyI6ImNvZ25pdGl2ZXNjYWxlLmNvbSJ9.EwFYL18rSUYtTu4eW6FJVGoNZ4ww31B2vIlQQpaXy8C1Fn-xzwJ92Ix3yi9hkIUnuUC6qyMFSfsXxztOLNjPDQ

###
GET http://localhost:4444/fabric/v4/projects/johan/activations/{{JobactivationId}}?report=true
Content-Type: application/json
Authorization: bearer eyJraWQiOiJfM1g1aWpvcGdTSm0tSmVmdWJQenh5RS1XWGw3UzJqSVZDLXRNWnNiRG9BIiwiYWxnIjoiRWREU0EifQ.eyJiZWFyZXIiOiJ1c2VyIiwiaWF0IjoxNjA0Njg1NDk2LCJleHAiOjE2MDQ3NzE4OTYsInN1YiI6IjM3MGY3ZWM2LTQ2NmYtNGEzNi1iYjVmLWJjMjRmMzRkYTIxYiIsImF1ZCI6ImNvcnRleCIsImlzcyI6ImNvZ25pdGl2ZXNjYWxlLmNvbSJ9.EwFYL18rSUYtTu4eW6FJVGoNZ4ww31B2vIlQQpaXy8C1Fn-xzwJ92Ix3yi9hkIUnuUC6qyMFSfsXxztOLNjPDQ

###
POST http://localhost:4444/fabric/v4/projects/johan/activations/544287db-f406-4b7a-8447-1370be8c225b/cancel
Content-Type: application/json
Authorization: bearer eyJraWQiOiJfM1g1aWpvcGdTSm0tSmVmdWJQenh5RS1XWGw3UzJqSVZDLXRNWnNiRG9BIiwiYWxnIjoiRWREU0EifQ.eyJiZWFyZXIiOiJ1c2VyIiwiaWF0IjoxNjA0Njg1NDk2LCJleHAiOjE2MDQ3NzE4OTYsInN1YiI6IjM3MGY3ZWM2LTQ2NmYtNGEzNi1iYjVmLWJjMjRmMzRkYTIxYiIsImF1ZCI6ImNvcnRleCIsImlzcyI6ImNvZ25pdGl2ZXNjYWxlLmNvbSJ9.EwFYL18rSUYtTu4eW6FJVGoNZ4ww31B2vIlQQpaXy8C1Fn-xzwJ92Ix3yi9hkIUnuUC6qyMFSfsXxztOLNjPDQ
